### ISSUE TITLE
Uncaught TypeError: $(...).unload is not a function

### ISSUE THREAD

**Issue by ericft** [joshp23/YOURLS-Expiry#11] opened 2019-06-06 20:01 UTC
Hi,

On YOURLS 1.7.4, I have an error with the function unload, I tried to change the method to on.('unload'...), it removed the error but the expiring time won't work and in the Expiry List the timer gives me a negative number, ex: -1d 0-1h0-1:0-22

Thanks in advance!

**Comment by joshp23** [comment] 2019-06-06 20:39
Odd, I'm not experiencing this bug, and run the latest from master. `unload` appears only [once](https://github.com/joshp23/YOURLS-Expiry/blob/master/expiry/plugin.php#L458) in Expiry, however it appears as if it has been removed from jQuerry since [3.0](https://www.w3schools.com/jquery/event_unload.asp). Maybe this weekend I can update. I will gladly merge an appropriate pull request.

**Comment by vitalyzhakov** [comment] 2019-12-21 04:47
@ericft , hello!
How we may reproduce situation?

**Comment by vitalyzhakov** [comment] 2019-12-25 05:27
@joshp23 , hello!
May be close this issue with not reproducing status?

**Closed as completed** 2020-03-01 06:51 UTC
